# Generated by Django 5.0 on 2023-12-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Completed', 'Completed'), ('no available', 'Not Available'), ('cannot diliver right now', 'Cannot Dilever right now'), ('arriving', 'Arriving')], default='pending', max_length=50),
        ),
    ]
