# Generated by Django 5.0 on 2023-12-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_carouselimage_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
