# Generated by Django 5.0 on 2023-12-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='order',
            name='otp_secret',
        ),
    ]
